### ISSUE TITLE
Doesn't Support iOS 9 Simulator

### ISSUE THREAD

**Issue by jamaljohnson** [Telerik-Verified-Plugins/TouchID#1]
The isAvailable method in the plugin returns false simply if it's the Simulator. As of iOS 9 simulator, TouchID can be emulated.  What we did was remove the check for Simulator in that method:

`
if (TARGET_IPHONE_SIMULATOR) {
    [self.commandDelegate sendPluginResult:[CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsString:@"The simulator is not supported"] callbackId:command.callbackId];
    return;
}
`

And everything works as expected. If it's the Simulator < iOS 9, the error returned is the expected simulator not supported error. 

If the Simulator is iOS 9 or greater, there will either be an error returned stating there are no fingerprints configured or no error at all if you have the Simulator setup to enable TouchID.

This makes testing surrounding TouchID easier.

**Comment by EddyVerbruggen** [comment]
Cool, thanks for letting me know, I'll add something like `!isAtLeastVersion("9")`.

**Comment by jamaljohnson** [comment]
Why not remove that conditional and let the OS handle it?

If you don't want to remove the conditional, would you mind adding a "." at the end of your sentence so when we upgrade to your newer version it will still work out of the box for us? 

Your sentence says: ""The simulator is not supported" but iOS's message says: ""The simulator is not supported.", ending with a period.

Thank you very much.

**Comment by EddyVerbruggen** [comment]
Removed the check entirely. Awesome new simulator feature! I wished they offered the same level of support for 3D Touch.

Available in 2.0.1.

**Comment by jamaljohnson** [comment]
Awesome! Yeah, I agree :). Thanks
